### ISSUE TITLE
fix for the sound manager window for the background process and screen readers

### ISSUE THREAD

**Issue by aryanchoudharypro** [ORelio/Sound-Manager#8] opened 2024-08-07 14:47 UTC
so, if we close a window, sometimes my screen reader goes to the sound manager windo. i know that we don't have to close it and so i don't, but some of my other friends don't and they press alt+f4 and close the window wich kills the process. it would be good if this window could be hidden somehow, or could ignore the alt+f4 shortcut

**Comment by ORelio** [comment] 2024-08-07 16:24
For your information, this window is there to receive the session events to play logon/logoff. When there are no open window, the events are not sent to the program. The window is supposed to be hidden, it's not present in task bar or Alt+Tab, but seems like your screen reader managed to switch focus to it somehow. I'll try to fix that.

**Comment by aryanchoudharypro** [comment] 2024-08-08 02:51
i can send you a screen recording if you want

**Comment by aryanchoudharypro** [comment] 2024-08-08 15:34
o i know that the windo needs to be open and that's why i created this issue

**Comment by aryanchoudharypro** [comment] 2024-08-11 03:58
ok, so i have the recording ready. first i open this pc then close it, then i press windows + d sometimes to show the same behavior. https://drive.google.com/file/d/1b-lKVjH-Cq5uVVHyftJeKtSiTxBnQ602/view?usp=sharing

**Comment by ORelio** [comment] 2024-08-11 15:07
Thanks. I'm still not sure how I will fix this.

**Comment by aryanchoudharypro** [comment] 2024-08-12 13:41
may be an event in the window to send win+d if someone presses alt+f4, if its doable

**Comment by ORelio** [comment] 2024-09-18 19:47
Hi,

I tried using NVDA with SoundManager but could not reproduce. NVDA does not pick up the SoundManager window when using Alt+Tab. (although it plays correctly the accessibility labels added in 3.3.0, which is nice).

After some testing, I could come up with a trick that seems promising : The window starts minimized, and if somehow the window gets focused, it immediately minimizes again, refusing to take focus. This should prevent NVDA from saying the title loud, and the user from accidentally closing the window.

Since I cannot determine if this work better, would you please try this build and provide feedback?

📁 [sound-manager-v3.3.0 TEST 2024-09-18.zip](https://github.com/user-attachments/files/17049484/sound-manager-v3.3.0.TEST.2024-09-18.zip)

**Comment by aryanchoudharypro** [comment] 2024-09-20 03:35
tested on windows 11, works well!

**Comment by ORelio** [comment] 2024-09-20 09:07
Great! Added the change to the repository for inclusion in next release.
Meanwhile, you can keep using the test build.

**Comment by ORelio** [comment] 2024-09-22 17:29
Turns out that under some circumstances, the minimized window becomes visible next to the task bar, so keeping the window minimized does not work so reliably.

I could come up with another idea, which is overriding a property on the window telling it does not need to get focus on show, then minimize/unminimize when the window gets focus to that it loses focus immediately. Seems more reliable for not showing anything on screen, but could you please test that NVDA does not pick it up?

📁 [sound-manager-v3.3.0.TEST.2024-09-22.zip](https://github.com/user-attachments/files/17090606/sound-manager-v3.3.0.TEST.2024-09-22.zip)

**Comment by aryanchoudharypro** [comment] 2024-09-22 18:10
this version also works nice with nvda!

**Comment by aryanchoudharypro** [comment] 2024-09-22 18:35
1 thing is that  when i close a window with alt+f4, nvda sometimes says sound manager. the good thing is that i cannot close the sound manager window by exident as it quickly loozes focus

**Comment by ORelio** [comment] 2024-09-23 10:09
Here is another attempt:

📁 [issue-8_sound-manager-v3.3.0.TEST.2024-09-23.zip](https://github.com/user-attachments/files/17095717/issue-8_sound-manager-v3.3.0.TEST.2024-09-23.zip)

I naively tried to remove the window title, but NVDA was just saying "Unknown" instead. I could trick it into not saying anything by replacing the title with [U+FFFD � REPLACEMENT CHARACTER](https://en.wikipedia.org/wiki/Specials_(Unicode_block)) (used for unrepresentable characters), then restoring the title to its original value when shutting down, because it is shown on "This App is Preventing Shutdown" screen.

**Comment by aryanchoudharypro** [comment] 2024-10-05 17:16
this works good! i didn't have my laptop so i couldn't test it for a while but i did now and it works

**Comment by ORelio** [comment] 2024-10-08 20:03
Thanks for your feedback! I'll include the latest attempt into the main codebase for inclusion in the next release.

**Comment by aryanchoudharypro** [comment] 2024-10-09 13:31
though the Current implementation works great, Can there be something which? shifts the focus to the desktop? It's not necessary, but it will be useful.

**Comment by ORelio** [comment] 2024-10-09 16:46
Does the current implementation somehow prevents normal access to the desktop (Win+D)?

**Comment by ORelio** [comment] 2024-10-10 16:32
This would definitely cause unexpected behavior for users not using nvda, but I could add an opt-in setting for that. I'll look if there's an easy way to shift focus to desktop programmatically.

**Comment by ORelio** [comment] 2024-10-22 18:48
Found a way to pass focus to the desktop window if the SoundManager window gets focused:

📁 [issue-8_sound-manager-v3.3.0.TEST.2024-10-22.zip](https://github.com/user-attachments/files/17480807/issue-8_sound-manager-v3.3.0.TEST.2024-10-22.zip)

**Comment by aryanchoudharypro** [comment] 2024-10-23 14:58
wooooo it now works so much grate! thanks. in very very rair cases nvda says sound manager, but i guess that's fine as that's not anoying! again thanks for working on this ossem project!

**Comment by ORelio** [comment] 2024-10-23 16:50
Good to hear! Okay, I thought that with this fix, nvda would not pick up the window title so I had set it back to SoundManager. Here is the same build but with unreadable window title:

📁 [issue-8_sound-manager-v3.3.0.TEST.2024-10-23.zip](https://github.com/user-attachments/files/17495645/issue-8_sound-manager-v3.3.0.TEST.2024-10-23.zip)

**Comment by aryanchoudharypro** [comment] 2024-10-23 21:59
Thanks, works grate

**Closed** 2024-10-24 06:27 UTC

**Comment by ORelio** [comment] 2024-10-25 09:46
Feature included in [SoundManager v3.3.1](https://github.com/ORelio/Sound-Manager/releases/tag/v3.3.1).
