### ISSUE TITLE
Sound Manager Two Users Issue

### ISSUE THREAD

**Issue by Howeitworks** [ORelio/Sound-Manager#2] opened 2023-12-15 05:23 UTC
Hi, I'm building my custom images for Windows 8, 8.1, 9, 10, and 11. When setting Sound Manager for two users it will play one or the other. Even if I install Sound Manager in Programs x86 as "Sound Manager" and "Sound Manager2" to attempt to setup schemes for each user, I have had no luck to figure out a work around to get both users (Admin account & User) to have Sound Manager. I have to choose one user or the other to have a scheme. If you may please share a work around or add compatibility to allow multiple users to share or have different schemes if possible. 

Thank you,
Andrew

**Comment by ORelio** [comment] 2023-12-17 18:34
Hi @Howeitworks,
Thanks for reporting this bug.
SoundManager stores its files and settings per-user indenpendently of installed/portable mode (except patching system startup sound on windows vista/7), so this definitely should not happen.
I'll investigate and try to reproduce your issue.

**Comment by ORelio** [comment] 2024-01-05 22:05
Hi,

Happy New Year 2024! 🎉 
Thanks again for reporting this issue and for your patience.

I was able to reproduce the issue. It was introduced in v3.0.2 when implementing #1: reducing startup sound delay by using a Scheduled Task instead of Run key in Registry. The underlying bug was that once first user creates the SoundManager task, the second user cannot, because scheduled task names are unique across users. Worse, the app tries to access the scheduled task on startup to determine if launch on startup is currently enabled, and crashes due to not having permissions on the task.

Everything should be fixed as per commit 6a4f4e0b0a1a5013f0c80a67232d7bdce4e945a8 released today in [Sound Manager v3.1.1](https://github.com/ORelio/Sound-Manager/releases/tag/v3.1.1).

Regarding your custom system image, I'd suggest placing the files from zip release in `SoundManager` folder under `C:\Program Files (x86)`, then run `SoundManager.exe --setup` (e.g. using the `runas` command) for each target user account.

Let me know if anything is still not working as expected 🙂

**Closed by ORelio** 2024-01-05 22:05 UTC
